config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "hello_world", to: "hello_world#index"
  resources :favourites
  resources :venues
  resources :votes
  resources :reviews
  resources :searches
  resources :performances
  resources :events
  resources :comments
  resources :comment_vote
  resources :list_items
  resources :friends
  resources :friend_requests

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "search" => "search#index"
  get "search/results" => "search#do_search"

  root to: redirect('/home/2019')

  get "/events/:id/comments" => "events#comments"
  get "/events/:id/is_favourited" => "events#is_favourited"
  get "/admin/panel" => "admin#panel"
  get "/events/:id/votes" => "events#votes"
  get "/events/:id/performances" => "events#performances"
  get "/events/:id/reviews" => "events#reviews"

  post "/lists/swap_items" => "lists#swap_items"
  post "/lists/create_item" => "lists#create_item"
  post "/lists/destroy_item" => "lists#destroy_item"

  get "/home/search" => "home#search", as: "home_page_search"

  # resources :search
  devise_for :users, controllers: {
    sessions: "users/sessions", invitations: 'users/invitations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "home/:year" => "home#events", :constraints => { year: /\d{4}/ }

  resources :credentials, only: [:create, :destroy] do
    post :callback, on: :collection
  end

  resource :webauthn_registration, only: [:new, :create] do
    post :callback
  end

  resources :credentials, only: [:create, :destroy] do
    post :callback, on: :collection
  end

  resource :webauthn_session, only: [:new, :create, :destroy] do
    post :callback
  end

end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :list_items, -> { order(position: :asc) }, dependent: :destroy
  has_many :events, through: :list_items
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  validates_length_of :name, minimum: 1
  validates_inclusion_of :year, in: Fringebot::YEARS

  scope :for_year, ->(year) { where(year: year) }

  # validates :year, inclusion: { in: Fringebot::YEARS,
    # message: "%{value} is not a valid year" }

  has_and_belongs_to_many :users

  # belongs_to :user

  def user_has_access?(user)
    users.include?(user)
  end

  def add_user(user, current_user)
    return false if user == current_user

    users << user
  end

  def remove_user(user, current_user)
    return false if user == current_user
    return false unless current_user == owner

    users.delete(user)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :check_for_access, except: [:index, :new, :create]

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @events = @list.events
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit; end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.owner = current_user
    @list.users << current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    if params[:add_user] == "true" || params[:remove_user] == "true"
      subject = User.find(params[:user_id])
      @list.add_user(subject, current_user) if params[:add_user] && !@list.users.include?(subject)
      @list.remove_user(subject, current_user) if params[:remove_user] && @list.owner == current_user

      respond_to do |format|
        format.html { redirect_to action: "show", notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      end
      return
    end

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to action: "index", notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def swap_items
    list = List.find(params[:listId].to_i)
    list_item = list.list_items.find_by_position(params[:oldIndex].to_i)
    list_item.insert_at(params[:newIndex].to_i)
    render json: { success: true }, status: 200
  end

  def create_item
    puts(params[:list_id], params[:event_id])
    @list_item = ListItem.new(list_id: params[:list_id], event_id: params[:event_id])
    @list_item.save!
    # @list_item.save!
    render json: @list_item.to_json, status: 200
  end

  def destroy_item
    puts(params[:list_id], params[:event_id])
    @list_item = List.find(params[:list_id]).list_items.find_by_event_id(params[:event_id])
    render json: @list_item.destroy, status: 200
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def list_params
    params.require(:list).permit(:user_id, :name, :year)
  end

  def list_swap_params
    params.permit(:oldIndex, :newIndex, :listId)
  end

  def check_for_access
    if !@list.users.include?(current_user)
      redirect_to lists_path
    end
  end
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
  def friend_action(user)
    # if !current_user.friends_with?(user)
    #   return content_tag(:span, "Friend", {
    #     data: {
    #       action: "click->friend-list#friendUser",
    #       user_id: user.id,
    #     },
    #     style: "cursor: pointer;",
    #     class: "pull-right",
    #   })
    # end
  end

  def separator
    return content_tag(:span, "&nbsp;|&nbsp;".html_safe, {class: "pull-right"})
  end

  def user_list_action(user)
    if user == current_user
      return
    end

    if current_user == @list.owner
      return content_tag(:span, "Remove", {
        data: {
          action: "click->friend-list#removeUser",
          user_id: user.id,
        },
        style: "cursor: pointer;",
        class: "pull-right",
      })
    end
  end
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true, :class => 'form-group col-xs-4') do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :name, :class => 'form-control', :type => 'text' %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.select(:year, options_for_select(Fringebot::YEARS.reverse, Fringebot::YEARS.last), { include_blank: false }, :class => 'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'btn btn-default' %>

  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<div class=' col-xs-12'>
  <%= link_to 'Show', @list %> |
  <%= link_to 'Back', lists_path %>
</div>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-12 col-md-6">

    <% Fringebot::YEARS.reverse.each do |year| %>
      <h3><%= year %></h3>
      <ul class="list-group">
        <% @lists.for_year(year).map do |list| %>
        <a href="/lists/<%= list.id %>">
          <li class="list-group-item panel-title"><%= list.name %></li>
        </a>
        <% end %>
      </ul>
    <% end %>
    <%= link_to 'New List', new_list_path, :class => 'btn btn btn-primary' %>

  </div>
  <div class="col-xs-6 col-md-4"></div>
</div>
<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<div class=' col-xs-12'>
  <%= link_to 'Back', lists_path %>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @list.name %></h2>

<div class="row" data-controller="friend-requests">
  <div class="col-md-6">
    <% @list.list_items.map(&:event_id).each do |event_id| %>
    <% event = Event.find(event_id) %>
    <%= render :partial => "home/event_card", locals: { event: event } %>
    <% end %>
  </div>


  <div class="col-md-6">

    <div class="panel panel-primary home_card text-info" data-controller="friend-list" data-list-id="<%= @list.id %>">
      <div class='panel-heading'>
        <h3 class="panel-title">Add friends to list</h3>
      </div>

      <div class="container-fluid" id="home-card">
        <!--           <div class="col-lg-6"> -->
          <div class="input-group">
            <select type="text" class="form-control" placeholder="Search for..." data-target="friend-list.userSelect">
              <% (current_user.friends - @list.users).each do |friend| %>
              <option value="<%= friend.id %>"><%= [friend.username, friend.email].join(" - ") %></option>
              <% end %>
              option
            </select>
            <span class="input-group-btn">
              <button class="btn btn-default" type="button" data-action="friend-list#addUser">Add to list</button>
            </span>
          </div><!-- /input-group -->
        </div><!-- /input-group -->

        <div>
          <ul class="list-group">
          <h4><strong>Users in list</strong></h4>
            <% (@list.users - [current_user]).each do |user| %>
              <li class="list-group-item"><%= user.email %>
                <%= user_list_action(user) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


<div class=' col-xs-12'>
  <%= link_to 'Back', lists_path %> |
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to "Delete", list_path(@list), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
</div>